"""Initial Migration

Revision ID: 516a71a9837b
Revises: 
Create Date: 2023-08-02 12:36:19.509764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516a71a9837b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
